#!/bin/bash

PKGNAME="neofetch"
PKGVER="7.1.0"
PKGBUILD="$HOME/src/ipm/tmp/$PKGNAME"
PKGTARGET="$HOME/.local/usr"

if [ "$1" == "i" ]; then
  cd "$PKGBUILD"
  wget "https://github.com/dylanaraps/neofetch/archive/refs/tags/$PKGVER.tar.gz"
  tar -xvf "$PKGVER.tar.gz"
  cd "$PKGNAME-$PKGVER"
  make PREFIX="$PKGTARGET" install
  rm -rf *.md
  exit 0
elif [ "$1" == "r" ]; then
  make PREFIX="$PKGTARGET" uninstall
  rm -rf $PKGBUILD
  exit 0
else
  echo "opção desconhecida"
  exit 1
fi
